/**
 * Maps semantic icon names and legacy emoji keys → Phosphor icon components.
 * Weight is applied in Icon.jsx (default: light).
 */
import {
  Airplane,
  ArrowDown,
  ArrowUp,
  ArrowsClockwise,
  Baby,
  BabyCarriage,
  Backpack,
  Bank,
  Barbell,
  Bathtub,
  BeachBall,
  Bell,
  Bird,
  BookOpen,
  Books,
  Broom,
  Bug,
  Buildings,
  Calendar,
  Camera,
  Car,
  ChartBar,
  Check,
  Circle,
  Clipboard,
  Clock,
  Confetti,
  CookingPot,
  Cow,
  Drop,
  Eye,
  FirstAid,
  Flag,
  Flower,
  Football,
  ForkKnife,
  Gift,
  Globe,
  GlobeHemisphereWest,
  GlobeStand,
  GraduationCap,
  Hand,
  HandPointing,
  HandsClapping,
  Handshake,
  HandWaving,
  Heart,
  HeartStraight,
  Hospital,
  Hourglass,
  House,
  Ladder,
  Lightbulb,
  Link,
  MagnifyingGlass,
  MapTrifold,
  Medal,
  Megaphone,
  Microscope,
  Moon,
  Mountains,
  MusicNote,
  MusicNotes,
  Notebook,
  Package,
  PaintBrush,
  Palette,
  Paperclip,
  Pencil,
  Person,
  PersonSimple,
  PersonSimpleBike,
  PersonSimpleRun,
  PersonSimpleTaiChi,
  PersonSimpleWalk,
  Phone,
  Play,
  Printer,
  PuzzlePiece,
  Question,
  RadioButton,
  Scales,
  Scissors,
  Scroll,
  ShoppingCart,
  Sparkle,
  Star,
  Stethoscope,
  Student,
  Suitcase,
  Sun,
  SwimmingPool,
  Tag,
  Target,
  ThumbsUp,
  Timer,
  Toilet,
  TrafficSignal,
  Train,
  Tree,
  Trophy,
  TShirt,
  UserCircle,
  Users,
  Warning,
  X,
  ChatsCircle,
  Sneaker,
  Horse,
  Yarn,
  Info,
  Envelope,
  ShieldCheck,
  Cookie,
  PersonArmsSpread,
  FileText,
  InstagramLogo,
  TiktokLogo,
  PinterestLogo,
  YoutubeLogo,
  WhatsappLogo,
  FacebookLogo,
  XLogo,
  ShareNetwork,
} from '@phosphor-icons/react';

/** @type {Record<string, import('@phosphor-icons/react').Icon>} */
export const PHOSPHOR_ICON_MAP = {
  home: House,
  baby: Baby,
  heart: Heart,
  'shopping-cart': ShoppingCart,
  'speech-bubble': ChatsCircle,
  luggage: Suitcase,
  calendar: Calendar,
  medical: FirstAid,
  stethoscope: Stethoscope,
  sparkles: Sparkle,
  check: Check,
  'check-mark': Check,
  close: X,
  play: Play,
  star: Star,
  'star-glow': Star,
  stopwatch: Timer,
  warning: Warning,
  target: Target,
  all: Target,
  printer: Printer,
  link: Link,
  globe: Globe,
  clipboard: Clipboard,
  microscope: Microscope,
  airplane: Airplane,
  train: Train,
  car: Car,
  tree: Tree,
  hotel: Buildings,
  books: Books,
  brain: Lightbulb,
  'flexed-bicep': Barbell,
  'light-bulb': Lightbulb,
  'thumbs-up': ThumbsUp,
  handshake: Handshake,
  party: Confetti,
  paperclip: Paperclip,
  bathtub: Bathtub,
  'raised-hand': Hand,
  'palms-up': HandWaving,
  't-shirt': TShirt,
  'baby-bottle': BabyCarriage,
  'two-hearts': HeartStraight,
  hugging: HandsClapping,
  cartwheel: PersonSimpleTaiChi,
  backpack: Backpack,
  lotion: Drop,
  soap: Drop,
  'bar-chart': ChartBar,
  plate: ForkKnife,
  'crescent-moon': Moon,
  'book-open': BookOpen,
  info: Info,
  envelope: Envelope,
  shield: ShieldCheck,
  scales: Scales,
  cookie: Cookie,
  accessibility: PersonArmsSpread,
  document: FileText,
  question: Question,
  instagram: InstagramLogo,
  tiktok: TiktokLogo,
  pinterest: PinterestLogo,
  youtube: YoutubeLogo,
  whatsapp: WhatsappLogo,
  facebook: FacebookLogo,
  x: XLogo,
  share: ShareNetwork,
  'share-network': ShareNetwork,
  copy: Link,
  timer: Timer,

  '1f300': Sparkle,
  '1f308': Sun,
  '1f30d': GlobeHemisphereWest,
  '1f310': GlobeStand,
  '1f342': Flower,
  '1f373': CookingPot,
  '1f382': Gift,
  '1f393': GraduationCap,
  '1f3a4': Megaphone,
  '1f3a8': PaintBrush,
  '1f3ad': Palette,
  '1f3b2': Target,
  '1f3b5': MusicNote,
  '1f3b6': MusicNotes,
  '1f3be': Trophy,
  '1f3c3': PersonSimpleRun,
  '1f3c4': PersonSimpleRun,
  '1f3c5': Medal,
  '1f3c8': Football,
  '1f3d4': Mountains,
  '1f3d7': Buildings,
  '1f3d8': House,
  '1f3db': Bank,
  '1f3e5': Hospital,
  '1f3eb': Student,
  '1f3f0': Buildings,
  '1f3f7': Tag,
  '1f404': Cow,
  '1f41b': Bug,
  '1f42d': Bug,
  '1f434': Horse,
  '1f440': Eye,
  '1f446': HandPointing,
  '1f44b': HandWaving,
  '1f44f': HandsClapping,
  '1f468-200d-1f469-200d-1f467': Users,
  '1f468-200d-1f469-200d-1f467-200d-1f466': Users,
  '1f468-200d-2695': Stethoscope,
  '1f46b': Users,
  '1f483': MusicNotes,
  '1f4a7': Drop,
  '1f4ad': ChatsCircle,
  '1f4c5': Calendar,
  '1f4cf': Scroll,
  '1f4d0': Target,
  '1f4d3': Notebook,
  '1f4d6': BookOpen,
  '1f4dc': Scroll,
  '1f4dd': Pencil,
  '1f4e6': Package,
  '1f4f1': Phone,
  '1f4f7': Camera,
  '1f4ff': Heart,
  '1f504': ArrowsClockwise,
  '1f50d': MagnifyingGlass,
  '1f514': Bell,
  '1f518': RadioButton,
  '1f522': Target,
  '1f52c': Microscope,
  '1f534': Circle,
  '1f58d': Pencil,
  '1f5bc': Palette,
  '1f5e3': Megaphone,
  '1f5fa': MapTrifold,
  '1f60a': Heart,
  '1f648': UserCircle,
  '1f6a6': TrafficSignal,
  '1f6b2': PersonSimpleBike,
  '1f6b4': PersonSimpleBike,
  '1f6b6': PersonSimpleWalk,
  '1f6bd': Toilet,
  '1f6dd': Tree,
  '1f914': Lightbulb,
  '1f931': Person,
  '1f941': MusicNotes,
  '1f944': ForkKnife,
  '1f97e': Sneaker,
  '1f997': Bug,
  '1f998': Horse,
  '1f9a9': Bird,
  '1f9b5': PersonSimpleRun,
  '1f9b6': PersonSimpleWalk,
  '1f9cd': PersonSimpleWalk,
  '1f9d1': Person,
  '1f9d7': Ladder,
  '1f9d8': PersonSimpleTaiChi,
  '1f9e6': TShirt,
  '1f9e9': PuzzlePiece,
  '1f9f1': Buildings,
  '1f9f5': Yarn,
  '1f9f8': Gift,
  '1f9f9': Broom,
  '1fa91': PersonSimple,
  '1fa9c': Ladder,
  '1fa9e': UserCircle,
  '1faa3': SwimmingPool,
  '1fae7': BeachBall,
  '1f0cf': Sparkle,
  '1f1ee-1f1f3': Flag,
  '1f1fa-1f1f8': Flag,
  '2696': Scales,
  '26bd': Football,
  '2702': Scissors,
  '2753': Question,
  '⬆️': ArrowUp,
  '⬇️': ArrowDown,
  '⏰': Clock,
  '⏳': Hourglass,
};

const DEFAULT_ICON = Sparkle;

/**
 * @param {string | null | undefined} name
 * @returns {import('@phosphor-icons/react').Icon}
 */
export function resolvePhosphorIcon(name) {
  if (!name) return DEFAULT_ICON;
  if (PHOSPHOR_ICON_MAP[name]) return PHOSPHOR_ICON_MAP[name];

  const parts = [];
  for (const char of name) {
    const cp = char.codePointAt(0);
    if (cp === 0xfe0f) continue;
    parts.push(cp.toString(16));
  }
  const codeKey = parts.join('-');
  if (PHOSPHOR_ICON_MAP[codeKey]) return PHOSPHOR_ICON_MAP[codeKey];

  return DEFAULT_ICON;
}
